apiVersion: v1
kind: ConfigMap
metadata:
  name: nc-script
  namespace: kube-system
data:
  entrypoint.sh: |-
    #!/bin/sh
    apk add netcat-openbsd sed
    for i in $(seq $START_PORT $END_PORT); do
      nc -lk $i | sed -u s/^/NC:$(hostname -i):$i:/ &
    done
    nc -ukl $(echo $START_PORT+1 | bc) | sed -u s/^/NC:$(hostname -i):$(echo $START_PORT+1 | bc):/ &
    sleep 1
    touch /ready
    sleep 1d
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nc
  namespace: kube-system
  labels:
    name: nc
spec:
  selector:
    matchLabels:
      name: nc
  minReadySeconds: 0
  template:
    metadata:
      labels:
        name: nc
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: px/enabled
                operator: NotIn
                values:
                - "false"
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
      hostNetwork: true
      terminationGracePeriodSeconds: 0
      volumes:
      - name: nc-script
        configMap:
          defaultMode: 0700
          name: nc-script
      hostNetwork: true
      containers:
        - name: nc
          image: alpine:3.10.3
          command:
          - /entrypoint.sh
          readinessProbe:
            exec:
              command:
              - cat
              - /ready
            initialDelaySeconds: 1
            periodSeconds: 1
          volumeMounts:
          - name: nc-script
            mountPath: /entrypoint.sh
            readOnly: true
            subPath: entrypoint.sh
          env:
            - name: START_PORT
              valueFrom:
                configMapKeyRef:
                  name: preflight-config
                  key: start_port
            - name: END_PORT
              valueFrom:
                configMapKeyRef:
                  name: preflight-config
                  key: end_port
            - name: NODES
              valueFrom:
                configMapKeyRef:
                  name: preflight-config
                  key: nodes
