apiVersion: v1
kind: Namespace
metadata:
  name: px-preflight
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: px-preflight
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: px-preflight
        imagePullPolicy: "Never"
        ports:
        - containerPort: 5432
        command:
        - "su"
        - "-"
        - "postgres"
        - "-c"
        - "/usr/lib/postgresql/12/bin/postgres -c config_file=/etc/postgresql/12/main/postgresql.conf -h '*'"
        readinessProbe:
          exec:
            command: ["psql", "-U", "postgres", "-c", "SELECT 1"]
          initialDelaySeconds: 1
          timeoutSeconds: 2
          periodSeconds: 5
        livenessProbe:
          exec:
            command: ["psql", "-U", "postgres", "-c", "SELECT 1"]
          initialDelaySeconds: 1
          timeoutSeconds: 2
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: px-preflight
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: px-preflight
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: px-preflight
        imagePullPolicy: "Never"
        ports:
        - containerPort: 80
        command:
        - "nginx"
        - "-g"
        - "daemon off;"
        readinessProbe:
          httpGet:
            port: 80
            path: /index.html
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            port: 80
            path: /index.html
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 1
